package pojo;
// Generated Dec 16, 2021, 3:29:01 PM by Hibernate Tools 5.5.7.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * DienThoai generated by hbm2java
 */
public class DienThoai implements java.io.Serializable {

	private int maDt;
	private DanhMuc danhMuc;
	private NhaSanXuat nhaSanXuat;
	private String tenDt;
	private byte[] hinhAnh;
	private String base64image;
	private String moTa;
	private String manHinh;
	private String heDieuHanh;
	private String cameraTruoc;
	private String cameraSau;
	private String chip;
	private String ram;
	private String rom;
	private String sim;
	private String pin;
	private double giaBan;
	private int tonKho;
	private int giamGia;
	private Double thanhTien;
	private String hienThiGiaBan;
	private String hienThiThanhTien;
	private Set chiTietGioHangs = new HashSet(0);

	public DienThoai() {
	}

	public DienThoai(int maDt, DanhMuc danhMuc, NhaSanXuat nhaSanXuat, String tenDt, double giaBan, int tonKho,
			int giamGia, String hienThiGiaBan, String hienThiThanhTien) {
		this.maDt = maDt;
		this.danhMuc = danhMuc;
		this.nhaSanXuat = nhaSanXuat;
		this.tenDt = tenDt;
		this.giaBan = giaBan;
		this.tonKho = tonKho;
		this.giamGia = giamGia;
		this.hienThiGiaBan = hienThiGiaBan;
		this.hienThiThanhTien = hienThiThanhTien;
	}

	public DienThoai(int maDt, DanhMuc danhMuc, NhaSanXuat nhaSanXuat, String tenDt, byte[] hinhAnh,
			String base64image, String moTa, String manHinh, String heDieuHanh,
			String cameraTruoc, String cameraSau, String chip, String ram, String rom,
			String sim, String pin, double giaBan, int tonKho, int giamGia, Double thanhTien,
			String hienThiGiaBan, String hienThiThanhTien, Set chiTietGioHangs) {
		this.maDt = maDt;
		this.danhMuc = danhMuc;
		this.nhaSanXuat = nhaSanXuat;
		this.tenDt = tenDt;
		this.hinhAnh = hinhAnh;
		this.base64image = base64image;
		this.moTa = moTa;
		this.manHinh = manHinh;
		this.heDieuHanh = heDieuHanh;
		this.cameraTruoc = cameraTruoc;
		this.cameraSau = cameraSau;
		this.chip = chip;
		this.ram = ram;
		this.rom = rom;
		this.sim = sim;
		this.pin = pin;
		this.giaBan = giaBan;
		this.tonKho = tonKho;
		this.giamGia = giamGia;
		this.thanhTien = thanhTien;
		this.hienThiGiaBan = hienThiGiaBan;
		this.hienThiThanhTien = hienThiThanhTien;
		this.chiTietGioHangs = chiTietGioHangs;
	}

	public int getMaDt() {
		return this.maDt;
	}

	public void setMaDt(int maDt) {
		this.maDt = maDt;
	}

	public DanhMuc getDanhMuc() {
		return this.danhMuc;
	}

	public void setDanhMuc(DanhMuc danhMuc) {
		this.danhMuc = danhMuc;
	}

	public NhaSanXuat getNhaSanXuat() {
		return this.nhaSanXuat;
	}

	public void setNhaSanXuat(NhaSanXuat nhaSanXuat) {
		this.nhaSanXuat = nhaSanXuat;
	}

	public String getTenDt() {
		return this.tenDt;
	}

	public void setTenDt(String tenDt) {
		this.tenDt = tenDt;
	}

	public byte[] getHinhAnh() {
		return this.hinhAnh;
	}

	public void setHinhAnh(byte[] hinhAnh) {
		this.hinhAnh = hinhAnh;
	}

	public String getBase64image() {
		return this.base64image;
	}

	public void setBase64image(String base64image) {
		this.base64image = base64image;
	}

	public String getMoTa() {
		return this.moTa;
	}

	public void setMoTa(String moTa) {
		this.moTa = moTa;
	}

	public String getManHinh() {
		return this.manHinh;
	}

	public void setManHinh(String manHinh) {
		this.manHinh = manHinh;
	}

	public String getHeDieuHanh() {
		return this.heDieuHanh;
	}

	public void setHeDieuHanh(String heDieuHanh) {
		this.heDieuHanh = heDieuHanh;
	}

	public String getCameraTruoc() {
		return this.cameraTruoc;
	}

	public void setCameraTruoc(String cameraTruoc) {
		this.cameraTruoc = cameraTruoc;
	}

	public String getCameraSau() {
		return this.cameraSau;
	}

	public void setCameraSau(String cameraSau) {
		this.cameraSau = cameraSau;
	}

	public String getChip() {
		return this.chip;
	}

	public void setChip(String chip) {
		this.chip = chip;
	}

	public String getRam() {
		return this.ram;
	}

	public void setRam(String ram) {
		this.ram = ram;
	}

	public String getRom() {
		return this.rom;
	}

	public void setRom(String rom) {
		this.rom = rom;
	}

	public String getSim() {
		return this.sim;
	}

	public void setSim(String sim) {
		this.sim = sim;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public double getGiaBan() {
		return this.giaBan;
	}

	public void setGiaBan(double giaBan) {
		this.giaBan = giaBan;
	}

	public int getTonKho() {
		return this.tonKho;
	}

	public void setTonKho(int tonKho) {
		this.tonKho = tonKho;
	}

	public int getGiamGia() {
		return this.giamGia;
	}

	public void setGiamGia(int giamGia) {
		this.giamGia = giamGia;
	}

	public Double getThanhTien() {
		return this.thanhTien;
	}

	public void setThanhTien(Double thanhTien) {
		this.thanhTien = thanhTien;
	}

	public String getHienThiGiaBan() {
		return this.hienThiGiaBan;
	}

	public void setHienThiGiaBan(String hienThiGiaBan) {
		this.hienThiGiaBan = hienThiGiaBan;
	}

	public String getHienThiThanhTien() {
		return this.hienThiThanhTien;
	}

	public void setHienThiThanhTien(String hienThiThanhTien) {
		this.hienThiThanhTien = hienThiThanhTien;
	}

	public Set getChiTietGioHangs() {
		return this.chiTietGioHangs;
	}

	public void setChiTietGioHangs(Set chiTietGioHangs) {
		this.chiTietGioHangs = chiTietGioHangs;
	}

}
