package pojo;
// Generated Dec 16, 2021, 3:12:49 PM by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * GioHang generated by hbm2java
 */
public class GioHang implements java.io.Serializable {

	private int maGh;
	private KhachHang khachHang;
	private double tongGiaTien;
	private String hienThiTongTien;
	private Set hoaDons = new HashSet(0);
	private Set chiTietGioHangs = new HashSet(0);

	public GioHang() {
	}

	public GioHang(int maGh, KhachHang khachHang, double tongGiaTien, String hienThiTongTien) {
		this.maGh = maGh;
		this.khachHang = khachHang;
		this.tongGiaTien = tongGiaTien;
		this.hienThiTongTien = hienThiTongTien;
	}

	public GioHang(int maGh, KhachHang khachHang, double tongGiaTien, String hienThiTongTien, Set hoaDons,
			Set chiTietGioHangs) {
		this.maGh = maGh;
		this.khachHang = khachHang;
		this.tongGiaTien = tongGiaTien;
		this.hienThiTongTien = hienThiTongTien;
		this.hoaDons = hoaDons;
		this.chiTietGioHangs = chiTietGioHangs;
	}

	public int getMaGh() {
		return this.maGh;
	}

	public void setMaGh(int maGh) {
		this.maGh = maGh;
	}

	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	public double getTongGiaTien() {
		return this.tongGiaTien;
	}

	public void setTongGiaTien(double tongGiaTien) {
		this.tongGiaTien = tongGiaTien;
	}

	public String getHienThiTongTien() {
		return this.hienThiTongTien;
	}

	public void setHienThiTongTien(String hienThiTongTien) {
		this.hienThiTongTien = hienThiTongTien;
	}

	public Set getHoaDons() {
		return this.hoaDons;
	}

	public void setHoaDons(Set hoaDons) {
		this.hoaDons = hoaDons;
	}

	public Set getChiTietGioHangs() {
		return this.chiTietGioHangs;
	}

	public void setChiTietGioHangs(Set chiTietGioHangs) {
		this.chiTietGioHangs = chiTietGioHangs;
	}

}
