package pojo;
// Generated Jan 1, 2022, 12:34:54 PM by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * HoaDon generated by hbm2java
 */
public class HoaDon implements java.io.Serializable {

	private int maHd;
	private KhachHang khachHang;
	private Integer status;
	private double tongTien;
	private String hienThiTongTien;
	private Set chiTietHoaDons = new HashSet(0);

	public HoaDon() {
	}

	public HoaDon(int maHd, KhachHang khachHang, double tongTien, String hienThiTongTien) {
		this.maHd = maHd;
		this.khachHang = khachHang;
		this.tongTien = tongTien;
		this.hienThiTongTien = hienThiTongTien;
	}

	public HoaDon(int maHd, KhachHang khachHang, Integer status, double tongTien, String hienThiTongTien,
			Set chiTietHoaDons) {
		this.maHd = maHd;
		this.khachHang = khachHang;
		this.status = status;
		this.tongTien = tongTien;
		this.hienThiTongTien = hienThiTongTien;
		this.chiTietHoaDons = chiTietHoaDons;
	}

	public int getMaHd() {
		return this.maHd;
	}

	public void setMaHd(int maHd) {
		this.maHd = maHd;
	}

	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public double getTongTien() {
		return this.tongTien;
	}

	public void setTongTien(double tongTien) {
		this.tongTien = tongTien;
	}

	public String getHienThiTongTien() {
		return this.hienThiTongTien;
	}

	public void setHienThiTongTien(String hienThiTongTien) {
		this.hienThiTongTien = hienThiTongTien;
	}

	public Set getChiTietHoaDons() {
		return this.chiTietHoaDons;
	}

	public void setChiTietHoaDons(Set chiTietHoaDons) {
		this.chiTietHoaDons = chiTietHoaDons;
	}

}
