package pojo;
// Generated Dec 16, 2021, 3:12:49 PM by Hibernate Tools 5.5.7.Final

/**
 * HoaDon generated by hbm2java
 */
public class HoaDon implements java.io.Serializable {

	private int maHd;
	private GioHang gioHang;
	private Integer status;

	public HoaDon() {
	}

	public HoaDon(int maHd, GioHang gioHang) {
		this.maHd = maHd;
		this.gioHang = gioHang;
	}

	public HoaDon(int maHd, GioHang gioHang, Integer status) {
		this.maHd = maHd;
		this.gioHang = gioHang;
		this.status = status;
	}

	public int getMaHd() {
		return this.maHd;
	}

	public void setMaHd(int maHd) {
		this.maHd = maHd;
	}

	public GioHang getGioHang() {
		return this.gioHang;
	}

	public void setGioHang(GioHang gioHang) {
		this.gioHang = gioHang;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
