package pojo;
// Generated Dec 16, 2021, 3:12:49 PM by Hibernate Tools 5.5.7.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * KhachHang generated by hbm2java
 */
public class KhachHang implements java.io.Serializable {

	private int maKh;
	private String taikhoan;
	private String matkhau;
	private String tenKh;
	private String sdt;
	private String diachi;
	private Set gioHangs = new HashSet(0);

	public KhachHang() {
	}

	public KhachHang(int maKh, String taikhoan, String matkhau, String tenKh, String sdt, String diachi) {
		this.maKh = maKh;
		this.taikhoan = taikhoan;
		this.matkhau = matkhau;
		this.tenKh = tenKh;
		this.sdt = sdt;
		this.diachi = diachi;
	}

	public KhachHang(int maKh, String taikhoan, String matkhau, String tenKh, String sdt, String diachi,
			Set gioHangs) {
		this.maKh = maKh;
		this.taikhoan = taikhoan;
		this.matkhau = matkhau;
		this.tenKh = tenKh;
		this.sdt = sdt;
		this.diachi = diachi;
		this.gioHangs = gioHangs;
	}

	public int getMaKh() {
		return this.maKh;
	}

	public void setMaKh(int maKh) {
		this.maKh = maKh;
	}

	public String getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(String taikhoan) {
		this.taikhoan = taikhoan;
	}

	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}

	public String getTenKh() {
		return this.tenKh;
	}

	public void setTenKh(String tenKh) {
		this.tenKh = tenKh;
	}

	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	public Set getGioHangs() {
		return this.gioHangs;
	}

	public void setGioHangs(Set gioHangs) {
		this.gioHangs = gioHangs;
	}

}
